import type { PreferredLanguage } from "../db/schema";

const screens = {
  tr: {
    common: {
      saved: "Kaydedildi",
      readOnly: "Salt okunur üyelik",
      readOnlyDescription: "Görüntüleyici rolü bilgileri inceleyebilir ancak değiştiremez.",
      status: "Supplier durumu",
      draftBoundary: "Kaydetme işlemi Supplier durumunu otomatik olarak aktifleştirmez.",
      locked: "Kilitli",
      view: "Görüntüle",
      continue: "Devam et",
      complete: "Tamamlandı",
      blocked: "Bloke",
      open: "Açık",
    },
    overview: {
      title: "Şirketinizi ticari aktivasyona hazırlayın",
      description:
        "Profil, katalog ve belge adımları birbirinden ayrı doğrulanır. Taslak durumdayken ticari etkileşim kapalı kalır.",
      onboardingAction: "Onboarding adımlarını aç",
      workspaceRequired: "Çalışma alanı gerekli",
      workspaceMissingTitle: "Tedarikçi çalışma alanı seçilmedi",
      workspaceMissingDescription:
        "Buyer hesabınızı koruyarak çalışma alanı tercihini “Her ikisi” olarak genişletebilirsiniz. Bu seçim tek başına ticari yetki vermez.",
      workspaceAction: "Çalışma alanını güncelle",
      identityBlocker: "Aktivasyon engeli",
      identityTitle: "İş kimliği doğrulaması tamamlanmadı",
      identityDescription:
        "Supplier şirketi, yalnızca doğrulanmış iş kimliği kanıtına bağlanarak oluşturulabilir.",
      identityAction: "İş kimliği durumunu görüntüle",
      emptyEyebrow: "Boş durum",
      emptyTitle: "Henüz Supplier şirketi oluşturulmadı",
      emptyDescription: "Doğrulanmış şirket kimliğiyle minimum şirket profilini oluşturarak başlayın.",
      createCompany: "Şirket profilini oluştur",
      activationEyebrow: "Aktivasyon durumu",
      activeTitle: "Tedarikçi aktif",
      inactiveTitle: "Ticari etkileşim henüz kapalı",
      activeDescription: "Aktif Supplier yetkileri bu hesaba ve şirkete göre uygulanır.",
      inactiveDescription:
        "Ürün taslakları hazırlanabilir; yayınlama, RFQ yanıtlama ve doğrudan talep alma belge onayından sonra açılır.",
      progressEyebrow: "Onboarding ilerlemesi",
      progressSuffix: "adım tamamlandı",
      productEyebrow: "Ürün özeti",
      productTitle: "0 ürün taslağı",
      productDescription: "Ürün oluşturma, ayrı bir ürün sihirbazı diliminde etkinleştirilecek.",
      productLocked: "Ürün oluşturma kilitli",
      rfqEyebrow: "Eşleşen RFQ akışı",
      rfqTitle: "Eşleşen RFQ yok",
      rfqDescription: "RFQ eşleştirme ve yanıtlama yalnızca aktif Supplier şirketlerine açılır.",
      enquiryEyebrow: "Talep akışı",
      enquiryTitle: "Doğrudan talep kapalı",
      enquiryDescription: "İletişim bilgileri ve ticari talepler aktivasyon tamamlanmadan görünmez.",
      documentsEyebrow: "Belge süre paneli",
      documentsTitle: "Belge takibi henüz başlamadı",
      documentsDescription:
        "Şirket belgesi yükleme, inceleme ve son-kullanma tarihi takibi issue #7’de açılacak.",
    },
    onboarding: {
      title: "Aktivasyon yolunu adım adım izleyin",
      description:
        "Tamamlanan profil adımları taslak hazırlığını ilerletir. Belge incelemesi bitmeden Supplier aktif olmaz.",
      completedSuffix: "tamamlandı",
      inspect: "Kaydı incele",
      completeAction: "Bu adımı tamamla",
      lockedDescription: "Bu adım ilgili güvenli modül birleştirildiğinde açılacak.",
      blockerEyebrow: "Engelleyici sorunlar",
      noBlockers: "Aktivasyon engeli yok",
      blockersSuffix: "açık engel var",
      dependencyBlocked: "Önceki bağımlılık veya sonraki modül bekleniyor.",
      userActionRequired: "Kullanıcı işlemi gerekli.",
      stateNotCreated: "supplier_not_created",
      activationWarning: "Checklist tamamlanması tek başına aktivasyon kararı üretmez.",
      documentsPending: "Belge modülü bekleniyor",
    },
    company: {
      createTitle: "Supplier şirketini oluşturun",
      updateTitle: "Şirket profilini güncelleyin",
      description:
        "Yasal şirket adı doğrulanmış iş kimliğiyle eşleşir. Profil kaydı şirketi aktif hale getirmez.",
      saved: "Şirket profili kaydedildi. Supplier durumu değişmeden korunuyor.",
      intentTitle: "Tedarikçi çalışma alanı izni yok",
      intentDescription: "Bu ekranı düzenlemek için çalışma alanı tercihini genişletin.",
      identityTitle: "Doğrulanmış iş kimliği gerekli",
      identityDescription: "Yasal şirket adı ancak doğrulanmış bir iş kimliği kaydına bağlanabilir.",
      identityAction: "Doğrulama durumunu aç",
      legalName: "Yasal şirket adı",
      verifiedName: "Doğrulanmış şirket adı",
      none: "henüz yok",
      tradingName: "Ticari ad",
      foundedYear: "Kuruluş yılı",
      countryCode: "Ülke kodu",
      countryHint: "İki harfli ülke kodu biçimi kullanılır.",
      city: "Şehir",
      website: "Web sitesi",
      descriptionLabel: "Şirket açıklaması",
      descriptionHint:
        "Ürün aileleri, hedef sektörler ve şirketin çalışma biçimini en az 20 karakterle açıklayın.",
      exportMarkets: "İhracat pazarları",
      exportHint: "İki harfli kodları virgül, boşluk veya noktalı virgülle ayırın.",
      mediaEyebrow: "Medya yükleyici",
      mediaTitle: "Şirket görselleri",
      mediaDescription:
        "Logo, tesis ve üretim fotoğrafı yükleme Cloudflare Images yapılandırmasıyla ayrı bir medya diliminde etkinleştirilecek.",
      mediaLocked: "Medya yükleme henüz kapalı",
      existing: "Mevcut şirket kaydı",
      newCompany: "Yeni Supplier şirketi",
      save: "Profili kaydet",
      create: "Şirketi oluştur",
      saving: "Kaydediliyor…",
      saveFailure: "Şirket profili kaydedilemedi. Lütfen yeniden deneyin.",
      intentFailure: "Önce Tedarikçi veya Her ikisi çalışma alanını seçin.",
      identityFailure: "Supplier şirketi için doğrulanmış iş kimliği gereklidir.",
      readOnlyFailure: "Bu üyelik şirket profilini yalnızca görüntüleyebilir.",
    },
    capabilities: {
      title: "Şirketinizin tedarik rolünü tanımlayın",
      description:
        "Birden fazla tedarikçi türü seçilebilir. Üretim kabiliyetleri yalnızca gerçekten yürüttüğünüz süreçler için işaretlenmelidir.",
      prerequisiteEyebrow: "Ön koşul",
      prerequisiteTitle: "Önce şirket profilini oluşturun",
      prerequisiteDescription: "Tür ve kabiliyet seçimleri identity-bound Supplier şirketine bağlanır.",
      prerequisiteAction: "Şirket profiline git",
      saved: "Tedarikçi türleri ve kabiliyetler kaydedildi. Supplier taslak durumu korunuyor.",
      typesEyebrow: "Tedarikçi türü kartları",
      typesTitle: "Tedarikçi türleri",
      multiple: "Çoklu seçim",
      contextsEyebrow: "Kullanım bağlamı seçici",
      contextsTitle: "Hizmet verdiğiniz kullanım bağlamları",
      minimumOne: "En az bir seçim",
      productionEyebrow: "Üretim kabiliyeti formu",
      productionTitle: "Üretim ve özelleştirme kabiliyetleri",
      optional: "İsteğe bağlı",
      productionDescription:
        "İhracatçı, dış ticaret şirketi veya distribütörseniz üretim kabiliyeti seçmeden profilinizi tamamlayabilirsiniz.",
      catalogueControlled: "Katalog kontrollü seçim",
      customDisabled: "Özel veya serbest metin tedarikçi türü eklenemez.",
      save: "Seçimleri kaydet",
      saving: "Kaydediliyor…",
      missingCompany: "Önce Supplier şirket profilini oluşturun.",
      readOnlyFailure: "Bu üyelik tedarikçi türlerini ve kabiliyetleri düzenleyemez.",
      saveFailure: "Tür ve kabiliyet seçimleri kaydedilemedi. Lütfen yeniden deneyin.",
    },
  },
  en: {
    common: {
      saved: "Saved",
      readOnly: "Read-only membership",
      readOnlyDescription: "The Viewer role can inspect this information but cannot change it.",
      status: "Supplier status",
      draftBoundary: "Saving does not automatically activate the Supplier company.",
      locked: "Locked",
      view: "View",
      continue: "Continue",
      complete: "Complete",
      blocked: "Blocked",
      open: "Open",
    },
    overview: {
      title: "Prepare your company for commercial activation",
      description:
        "Profile, catalogue and document steps are verified separately. Commercial interaction remains disabled while the company is a draft.",
      onboardingAction: "Open onboarding steps",
      workspaceRequired: "Workspace required",
      workspaceMissingTitle: "The Supplier workspace is not selected",
      workspaceMissingDescription:
        "You can preserve the Buyer workspace and expand the preference to Both. This choice alone does not grant commercial access.",
      workspaceAction: "Update workspace",
      identityBlocker: "Activation blocker",
      identityTitle: "Business identity verification is incomplete",
      identityDescription:
        "A Supplier company can only be created when it is bound to verified business-identity evidence.",
      identityAction: "View business identity status",
      emptyEyebrow: "Empty state",
      emptyTitle: "No Supplier company has been created",
      emptyDescription: "Start by creating the minimum company profile with the verified company identity.",
      createCompany: "Create company profile",
      activationEyebrow: "Activation status",
      activeTitle: "Supplier is active",
      inactiveTitle: "Commercial interaction is still disabled",
      activeDescription: "Active Supplier permissions are enforced for this account and company.",
      inactiveDescription:
        "Product drafts may be prepared; publishing, RFQ responses and direct enquiries open after document approval.",
      progressEyebrow: "Onboarding progress",
      progressSuffix: "steps complete",
      productEyebrow: "Product summary",
      productTitle: "0 product drafts",
      productDescription: "Product creation will be enabled in a separate product-wizard slice.",
      productLocked: "Product creation locked",
      rfqEyebrow: "Matched RFQ feed",
      rfqTitle: "No matched RFQs",
      rfqDescription: "RFQ matching and responses are available only to active Supplier companies.",
      enquiryEyebrow: "Enquiry feed",
      enquiryTitle: "Direct enquiries disabled",
      enquiryDescription: "Contact details and commercial enquiries remain hidden until activation.",
      documentsEyebrow: "Document expiry panel",
      documentsTitle: "Document tracking has not started",
      documentsDescription: "Company-document upload, review and expiry tracking will open in issue #7.",
    },
    onboarding: {
      title: "Follow the activation path step by step",
      description:
        "Completed profile steps advance draft preparation. The Supplier does not become active before document review is complete.",
      completedSuffix: "complete",
      inspect: "Inspect record",
      completeAction: "Complete this step",
      lockedDescription: "This step opens when the related secure module is merged.",
      blockerEyebrow: "Blocking issues",
      noBlockers: "No activation blockers",
      blockersSuffix: "open blockers",
      dependencyBlocked: "Waiting for a prior dependency or a later module.",
      userActionRequired: "User action required.",
      stateNotCreated: "supplier_not_created",
      activationWarning: "Completing the checklist does not itself create an activation decision.",
      documentsPending: "Waiting for document module",
    },
    company: {
      createTitle: "Create the Supplier company",
      updateTitle: "Update the company profile",
      description:
        "The legal company name must match verified business identity. Saving the profile does not activate the company.",
      saved: "Company profile saved. The Supplier status was preserved.",
      intentTitle: "Supplier workspace permission is missing",
      intentDescription: "Expand the workspace preference to edit this screen.",
      identityTitle: "Verified business identity required",
      identityDescription: "The legal company name can only be bound to a verified business-identity record.",
      identityAction: "Open verification status",
      legalName: "Legal company name",
      verifiedName: "Verified company name",
      none: "not available",
      tradingName: "Trading name",
      foundedYear: "Founded year",
      countryCode: "Country code",
      countryHint: "Use a two-letter country-code format.",
      city: "City",
      website: "Website",
      descriptionLabel: "Company description",
      descriptionHint:
        "Describe product families, target sectors and how the company operates using at least 20 characters.",
      exportMarkets: "Export markets",
      exportHint: "Separate two-letter codes with commas, spaces or semicolons.",
      mediaEyebrow: "Media uploader",
      mediaTitle: "Company media",
      mediaDescription:
        "Logo, facility and production-photo upload will be enabled in a separate media slice after Cloudflare Images configuration.",
      mediaLocked: "Media upload disabled",
      existing: "Existing company record",
      newCompany: "New Supplier company",
      save: "Save profile",
      create: "Create company",
      saving: "Saving…",
      saveFailure: "The company profile could not be saved. Please try again.",
      intentFailure: "Select the Supplier or Both workspace first.",
      identityFailure: "A verified business identity is required for the Supplier company.",
      readOnlyFailure: "This membership can only view the company profile.",
    },
    capabilities: {
      title: "Define your company’s Supplier role",
      description:
        "Multiple Supplier types may be selected. Mark only the production capabilities the company actually performs.",
      prerequisiteEyebrow: "Prerequisite",
      prerequisiteTitle: "Create the company profile first",
      prerequisiteDescription: "Type and capability selections are bound to the identity-linked Supplier company.",
      prerequisiteAction: "Go to company profile",
      saved: "Supplier types and capabilities saved. The Supplier draft status was preserved.",
      typesEyebrow: "Supplier type cards",
      typesTitle: "Supplier types",
      multiple: "Multiple selection",
      contextsEyebrow: "Application context selector",
      contextsTitle: "Application contexts served",
      minimumOne: "At least one selection",
      productionEyebrow: "Production capability form",
      productionTitle: "Production and customization capabilities",
      optional: "Optional",
      productionDescription:
        "Exporters, trading companies and distributors may complete the profile without selecting production capabilities.",
      catalogueControlled: "Catalogue-controlled selection",
      customDisabled: "Custom or free-text Supplier types cannot be added.",
      save: "Save selections",
      saving: "Saving…",
      missingCompany: "Create the Supplier company profile first.",
      readOnlyFailure: "This membership cannot edit Supplier types or capabilities.",
      saveFailure: "The type and capability selections could not be saved. Please try again.",
    },
  },
} as const;

export function supplierScreenCopy(language: PreferredLanguage) {
  return screens[language];
}
